name: Deployment Workflow
on: 
  push: 
    branches: [ main ]

jobs: 
  job_one: 
    name: Deploy
    runs-on: ubuntu-latest
    steps: 
    - name: testing SDCC server ssh connection
      uses: appleboy/ssh-action@master
      with: 
        host: 132.249.242.207
        username: nbalaji
        key: ${{ secrets.AUDINO_SECRET }}
        port: 22
        script: |
          cd ../sperry/Audio_Labeling_System_AID/audino
